[all:vars]
ansible_connection=community.general.incus
ansible_incus_remote=local
ansible_python_interpreter=/usr/bin/python3.13

[all]
ctl
api
core
db
mon
ceph

[control]
ctl

[app]
api
core

[database]
db

[monitoring]
mon

[storage]
ceph
